on: [push, pull_request]

jobs:
  build_job:
    name: 'Build'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ispeakcode/docker-githubaction
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
